public class q11 
{
	public static void test1()
    {
		List<List<String>> lList = new List<List<String>>();
        new List<String>{'a;b;a;v;c','x;x;y;c;q'};
        new List<String>{'m;b;h;j;m','u;k;j;u'};
        Set<Set<String>> sSet = new Set<Set<String>>();
        
            
        for(Integer i = 0; i < lList.size(); i++)
        {
        	for(Integer j = 0; j < lList[i].size(); j++)
            {
                String[] str = lList[i][j].split(';');
                Set<String> s = new Set<String>();
                
            }
        }

     }
}